### Carregando e limpando dados

In [22]:
import pandas as pd
import openpyxl

df = pd.read_excel("../data/Telco_customer_churn.xlsx")

df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [23]:
df = df.dropna()

#colunas que não são relevantes para a análise de churn e que trazem vazamentos/"spoilers" 
# para o modelo de machine learning colunas como churn label  ja nos trazem a resposta que nosso modelo ira trabalhar para buscar por isso removemos ela
df = df.drop(columns=[
    "Churn Label",
    "Churn Score",
    "Churn Reason"
])

In [24]:
y = df["Churn Value"]

In [25]:
X = df.drop(columns=["Churn Value"])
y = df["Churn Value"]

In [27]:
X = pd.get_dummies(X)
X

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,CLTV,CustomerID_0004-TLHLJ,CustomerID_0011-IGKFF,CustomerID_0013-EXCHZ,...,Total Charges_7690.9,Total Charges_7723.7,Total Charges_7723.9,Total Charges_7752.3,Total Charges_7804.15,Total Charges_7856.0,Total Charges_7968.85,Total Charges_8109.8,Total Charges_8127.6,Total Charges_8684.8
0,1,90003,33.964131,-118.272783,2,53.85,3239,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,90005,34.059281,-118.307420,2,70.70,2701,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1,90006,34.048013,-118.293953,8,99.65,5372,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1,90010,34.062125,-118.315709,28,104.80,5003,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1,90015,34.039224,-118.266293,49,103.70,5340,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1864,1,92264,33.745746,-116.514215,12,59.80,4581,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1865,1,92273,32.790282,-115.689559,9,44.20,2029,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1866,1,92280,34.264124,-114.717964,1,75.75,5571,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1867,1,92282,33.972293,-116.654195,67,102.95,5620,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1868,1,92307,34.550820,-117.122396,4,74.40,5839,False,False,False,...,False,False,False,False,False,False,False,False,False,False